-- ISCURRENTGEO Analysis

SELECT ISCURRENTGEO, ISEXTANT, count(*) from GIS.PARKLOTS_PY group by ISCURRENTGEO, ISEXTANT order by ISCURRENTGEO, ISEXTANT
select * from GIS.PARKLOTS_PY where ISCURRENTGEO <> 'Yes' or ISEXTANT <> 'True'
select * from GIS.PARKLOTS_PY where FEATUREID = '{57E5EF61-0F4B-4F62-A235-5BF3063A1248}'
select * from GIS.PARKLOTS_PY where FEATUREID in (select FEATUREID from GIS.PARKLOTS_PY where ISCURRENTGEO <> 'Yes') order by FEATUREID, ISCURRENTGEO

SELECT ISCURRENTGEO, ISEXTANT, count(*) from GIS.ROADS_LN group by ISCURRENTGEO, ISEXTANT order by ISCURRENTGEO, ISEXTANT
select FEATUREID, ISCURRENTGEO, RDNAME from GIS.ROADS_LN where FEATUREID in (select FEATUREID from GIS.ROADS_LN where ISCURRENTGEO <> 'Yes') order by FEATUREID, ISCURRENTGEO

SELECT ISCURRENTGEO, ISEXTANT, count(*) from GIS.TRAILS_LN group by ISCURRENTGEO, ISEXTANT order by ISCURRENTGEO, ISEXTANT
select FEATUREID, ISCURRENTGEO, TRLNAME from GIS.TRAILS_LN where FEATUREID in (select FEATUREID from GIS.TRAILS_LN where ISCURRENTGEO <> 'Yes') order by FEATUREID, ISCURRENTGEO
